---
title: "Data analysis"
author: "Ellie and Finn"
output:
  html_document:
    df_print: paged
---
```{r load-packages, message = FALSE}
library(tidyverse)
library(broom)
library(leaflet) ## For leaflet interactive maps
library(sf) ## For spatial data
library(RColorBrewer) ## For colour palettes
library(htmltools) ## For html
library(leafsync) ## For placing plots side by side
library(stringr) ## For character string manipulation
library(kableExtra) ## Table  output (in slides)
```

```{r vegetation file, echo = FALSE}
island_veg <- read_csv("../data/island_veg.csv")
```

```{r}
island_veg <- island_veg %>%
  mutate(location = case_when(
    location == "Schoodic" ~ "schoodic",
    location == "GDI" ~ "gdi",
    TRUE ~ location
  ))
```


```{r veg-barplot, fig.height=7, dev='jpeg'}
island_veg %>%
  filter(common != "unknown") %>% #filtering out all of the unknown species
  ggplot(mapping = aes(y = common)
    ) +
  geom_bar(fill = "#21918c") +
  facet_wrap(~location, nrow = 1) +
  theme(axis.text.y = element_text(vjust = 10)) +
  theme_minimal() + 
  labs(title = "Species disribution by island",
       x = "Number of occurences",
       y = "Common names")


# png("island_plot.png", width = 480, height = 480)
# island_veg %>%
#   filter(common != "unknown") %>% #filtering out all of the unknown species
#   ggplot(mapping = aes(y = common)
#     ) +
#   geom_bar(fill = "#21918c") +
#   facet_wrap(~location, nrow = 1) +
#   theme(axis.text.y = element_text(vjust = 10)) +
#   theme_minimal() + 
#   labs(title = "Species disribution by island",
#        x = "Number of occurences",
#        y = "Common names")
# dev.off()
```

```{r height-vis}
island_veg %>%
  mutate(height_class = case_when(TRUE ~ as.factor(height))) %>% #making height class a factor variable in order to use it in a bar chart
  ggplot(mapping = aes(x = location, fill = fct_rev(height_class))) + #reversing height class so the tallest appears on top
  geom_bar(position = "fill") +
  scale_fill_viridis_d() +
  labs(title = "Height classes on each island",
       x = "Island",
       y = "Proportion on height class",
       fill = "Height classes") +
  theme_minimal()
```

```{r}
gdi_bird <- st_read("../data/gull data/gdi_nests/gdi_nests_Merge.shp")
heron_bird <- st_read("../data/gull data/heron_nests/herg_nests_heron.shp")
#coei_schoodic_bird <- st_read("../data/gull data/schoodic_nests/coei_nests.shp")
#gbbg_schoodic_bird <- st_read("../data/gull data/schoodic_nests/gbbg_nests.shp")
#herg_schoodic_bird <- st_read("../data/gull data/schoodic_nests/herg_nests.shp")
schoodic_bird <- st_read("../data/gull data/schoodic_nests/all_nests.shp")
shabby_bird <- st_read("../data/gull data/shabby_nests/gull_eider_nests.shp")
```
```{r}
glimpse(schoodic_bird)
```

